#!/usr/bin/env bash

# Helper function to get remote DB credentials from Magento 2 env.php
# Usage: get_remote_db_info "REMOTE_DIR" ["ENV_NAME"]
# Returns: newline-separated list of DB_VAR=VALUE
function get_remote_db_info() {
    local remote_dir="$1"
    local env_name="${2:-${ENV_SOURCE}}"
    
    # Determine PHP command for local decoding
    # Prefer local php if available, otherwise use warden container
    local php_cmd="php"
    if ! command -v php &> /dev/null; then
        # Check if warden is available (should be since this is a warden command)
        if command -v warden &> /dev/null; then
             # We might need to ensure container is up, but usually 'exec' will scream if not.
             # We assume if no local php, user relies on warden containers.
             php_cmd="warden env exec -T php-fpm php"
        else
             printf "Error: 'php' command not found locally and 'warden' not available for fallback.\n" >&2
             return 1
        fi
    fi

    # Get remote DB credentials from env.php via base64 encoded JSON for maximum reliability
    local php_code="\$a=@include \"${remote_dir}/app/etc/env.php\"; echo base64_encode(json_encode(\$a['db']['connection']['default']));"
    local db_info_json=$(warden remote-exec -e "${env_name}" -- php -r "${php_code}" 2>/dev/null)
    
    if [[ -z "${db_info_json}" ]]; then
        return 1
    fi
    
    # Decode locally using determined php command
    local db_host=$(${php_cmd} -r "\$a = json_decode(base64_decode(\$argv[1]), true); echo strpos(\$a['host'] ?? 'db', ':') === false ? (\$a['host'] ?? 'db') : explode(':', \$a['host'])[0];" -- "${db_info_json}")
    local db_port=$(${php_cmd} -r "\$a = json_decode(base64_decode(\$argv[1]), true); echo strpos(\$a['host'] ?? '', ':') === false ? '3306' : explode(':', \$a['host'])[1];" -- "${db_info_json}")
    local db_user=$(${php_cmd} -r "\$a = json_decode(base64_decode(\$argv[1]), true); echo \$a['username'] ?? '';" -- "${db_info_json}")
    local db_pass=$(${php_cmd} -r "\$a = json_decode(base64_decode(\$argv[1]), true); echo \$a['password'] ?? '';" -- "${db_info_json}")
    local db_name=$(${php_cmd} -r "\$a = json_decode(base64_decode(\$argv[1]), true); echo \$a['dbname'] ?? '';" -- "${db_info_json}")
    
    echo "DB_HOST=${db_host}"
    echo "DB_PORT=${db_port}"
    echo "DB_USERNAME=${db_user}"
    echo "DB_PASSWORD=${db_pass}"
    echo "DB_DATABASE=${db_name}"
}

# List of tables to ignore during standard (no-noise flag) database dumps
IGNORED_TABLES=(
    'admin_system_messages'
    'admin_user_expiration'
    'admin_user_session'
    'adminnotification_inbox'
    'amasty_fpc_activity'
    'amasty_fpc_context_debug'
    'amasty_fpc_flushes_log'
    'amasty_fpc_job_queue'
    'amasty_fpc_log'
    'amasty_fpc_pages_to_flush'
    'amasty_fpc_queue_page'
    'amasty_fpc_reports'
    'amasty_mostviewed_product_index'
    'amasty_mostviewed_product_viewed_index'
    'amasty_mostviewed_product_viewed_index_replica'
    'amasty_reports_abandoned_cart'
    'amasty_reports_customers_customers_daily'
    'amasty_reports_customers_customers_monthly'
    'amasty_reports_customers_customers_weekly'
    'amasty_reports_customers_customers_yearly'
    'amasty_xsearch_users_search'
    'cache_tag'
    'catalog_category_product_cl'
    'catalog_category_product_index_replica'
    'catalog_category_product_index_tmp'
    'catalog_product_attribute_cl'
    'catalog_product_category_cl'
    'catalog_product_index_eav_decimal_idx'
    'catalog_product_index_eav_decimal_tmp'
    'catalog_product_index_eav_idx'
    'catalog_product_index_eav_replica'
    'catalog_product_index_eav_tmp'
    'catalog_product_index_price_bundle_idx'
    'catalog_product_index_price_bundle_opt_idx'
    'catalog_product_index_price_bundle_opt_tmp'
    'catalog_product_index_price_bundle_sel_idx'
    'catalog_product_index_price_bundle_sel_tmp'
    'catalog_product_index_price_bundle_tmp'
    'catalog_product_index_price_cfg_opt_agr_idx'
    'catalog_product_index_price_cfg_opt_agr_tmp'
    'catalog_product_index_price_cfg_opt_idx'
    'catalog_product_index_price_cfg_opt_tmp'
    'catalog_product_index_price_downlod_idx'
    'catalog_product_index_price_downlod_tmp'
    'catalog_product_index_price_final_idx'
    'catalog_product_index_price_final_tmp'
    'catalog_product_index_price_idx'
    'catalog_product_index_price_opt_agr_idx'
    'catalog_product_index_price_opt_agr_tmp'
    'catalog_product_index_price_opt_idx'
    'catalog_product_index_price_opt_tmp'
    'catalog_product_index_price_replica'
    'catalog_product_index_price_tmp'
    'catalog_product_price_cl'
    'cataloginventory_stock_cl'
    'cataloginventory_stock_status_idx'
    'cataloginventory_stock_status_tmp'
    'catalogsearch_fulltext_cl'
    'catalogsearch_fulltext_scope1'
    'catalogsearch_fulltext_scope2'
    'cron_schedule'
    'customer_grid_flat_cl'
    'customer_log'
    'customer_visitor'
    'design_config_grid_flat_cl'
    'elasticsuite_tracker_log_customer_link'
    'elasticsuite_tracker_log_event'
    'import_history'
    'inventory_cl'
    'inventory_stock_sales_channel_cl'
    'kiwicommerce_activity'
    'kiwicommerce_activity_detail'
    'kiwicommerce_activity_log'
    'klaviyo_sync_queue'
    'login_as_customer'
    'magento_bulk'
    'magento_logging_event'
    'magento_logging_event_changes'
    'magento_login_as_customer_log'
    'mageplaza_smtp_log'
    'mailchimp_errors'
    'mailchimp_sync_batches'
    'mailchimp_sync_ecommerce'
    'mailchimp_webhook_request'
    'mst_cache_warmer_job'
    'mst_cache_warmer_page'
    'mst_cache_warmer_trace'
    'mst_search_index_store'
    'mst_seo_audit_check_result_aggregated'
    'oauth_nonce'
    'oauth_token_request_log'
    'password_reset_request_event'
    'persistent_session'
    'queue_message'
    'queue_message_status'
    'report_compared_product_index'
    'report_event'
    'report_viewed_product_aggregated_daily'
    'report_viewed_product_aggregated_monthly'
    'report_viewed_product_aggregated_yearly'
    'report_viewed_product_index'
    'reporting_module_status'
    'reporting_system_updates'
    'reporting_users'
    'sales_bestsellers_aggregated_daily'
    'sales_bestsellers_aggregated_monthly'
    'sales_bestsellers_aggregated_yearly'
    'sales_invoiced_aggregated'
    'sales_invoiced_aggregated_order'
    'sales_order_aggregated_created'
    'sales_order_aggregated_updated'
    'sales_refunded_aggregated'
    'sales_refunded_aggregated_order'
    'sales_shipping_aggregated'
    'sales_shipping_aggregated_order'
    'search_query'
    'session'
    'sutunam_activity'
    'sutunam_activity_detail'
    'sutunam_activity_log'
    'ui_bookmark'
    'yotpo_order_sync'
    'yotpo_sync_queue'
)

# List of tables containing sensitive data to be ignored when --no-pii is passed
SENSITIVE_TABLES=(
    'admin_passwords'
    'admin_user'
    'aw_ca_company'
    'aw_ca_company_domain'
    'aw_ca_company_payments'
    'aw_ca_company_requisition_lists'
    'aw_ca_company_user'
    'aw_ca_group'
    'aw_ca_order_approval_state'
    'aw_ca_role'
    'aw_cl_credit_summary'
    'aw_cl_customer_group_credit_limit'
    'aw_cl_job'
    'aw_cl_transaction'
    'aw_cl_transaction_entity'
    'aw_cp_category_permissions'
    'aw_cp_cms_page_permissions'
    'aw_cp_product_permissions'
    'aw_ctq_comment'
    'aw_ctq_comment_attachment'
    'aw_ctq_history'
    'aw_ctq_quote'
    'aw_net30_order'
    'company'
    'company_advanced_customer_entity'
    'company_credit'
    'company_credit_history'
    'company_order_entity'
    'company_payment'
    'company_permissions'
    'company_roles'
    'company_shipping'
    'company_structure'
    'company_team'
    'company_user_roles'
    'customer_address_entity'
    'customer_address_entity_datetime'
    'customer_address_entity_decimal'
    'customer_address_entity_int'
    'customer_address_entity_text'
    'customer_address_entity_varchar'
    'customer_entity'
    'customer_entity_datetime'
    'customer_entity_decimal'
    'customer_entity_int'
    'customer_entity_text'
    'customer_entity_varchar'
    'customer_grid_flat'
    'downloadable_link_purchased'
    'downloadable_link_purchased_item'
    'email_automation'
    'email_contact'
    'magento_acknowledged_bulk'
    'magento_bulk'
    'magento_customerbalance'
    'magento_customerbalance_history'
    'magento_customersegment_customer'
    'magento_giftcardaccount'
    'magento_operation'
    'magento_reward'
    'magento_reward_history'
    'magento_rma'
    'magento_rma_grid'
    'magento_rma_item_entity'
    'magento_rma_shipping_label'
    'magento_rma_status_history'
    'magento_sales_creditmemo_grid_archive'
    'magento_sales_invoice_grid_archive'
    'magento_sales_order_grid_archive'
    'magento_sales_shipment_grid_archive'
    'mst_seo_audit_check_result_aggregated'
    'negotiable_quote_company_config'
    'newsletter_subscriber'
    'password_resets'
    'paypal_billing_agreement'
    'paypal_billing_agreement_order'
    'paypal_payment_transaction'
    'paypal_settlement_report'
    'paypal_settlement_report_row'
    'product_alert_price'
    'product_alert_stock'
    'purchase_order_company_config'
    'quote'
    'quote_address'
    'quote_address_item'
    'quote_id_mask'
    'quote_item'
    'quote_item_option'
    'quote_payment'
    'quote_shipping_rate'
    'sales_creditmemo'
    'sales_creditmemo_comment'
    'sales_creditmemo_grid'
    'sales_creditmemo_item'
    'sales_invoice'
    'sales_invoice_comment'
    'sales_invoice_grid'
    'sales_invoice_item'
    'sales_order'
    'sales_order_address'
    'sales_order_grid'
    'sales_order_item'
    'sales_order_payment'
    'sales_order_status_history'
    'sales_order_tax'
    'sales_order_tax_item'
    'sales_payment_transaction'
    'sales_shipment'
    'sales_shipment_comment'
    'sales_shipment_grid'
    'sales_shipment_item'
    'sales_shipment_track'
    'vault_payment_token'
    'vault_payment_token_order_payment_link'
    'wishlist'
    'wishlist_item'
    'wishlist_item_option'
)
